#include <iostream>
#include <random>
#include "Card.h"
#include <vector>

using namespace std;
enum Status {
    IN, OUT
};
int main() {
    // Create random number generator
    random_device random;
    mt19937 gen(random());

    int pot = 0;
    int numPlayers;
    do {
        cout << "Input number of players (2-10)" << endl;
        cin >> numPlayers;
    } while (numPlayers < 2 || numPlayers > 10);

    // DECK OF CARD Heh Heh Heh Heh Heh
    vector<Card> deck;
    char suits[4] = {'c', 'd', 'h', 's'};

    // 11=J 12=Q 13=K 14=A
    for (int i=2; i<=14; i++) {
        for (int j=0; j<=3; j++) {
            Card card;
            card.value = i;
            card.suit = suits[j];

            deck.push_back(card);
        }
    }

    // Set range of values generated by RNG
    uniform_int_distribution<> dis(0, numPlayers - 1);

    int dealer = dis(gen);
    int smallBlind = dealer + 1;
    int bigBlind = smallBlind + 1;

    return 0;
}

//void playHand(int& dealerPos, int& pot, )
